apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: bolg
    tier: frontend
    run: angular-bolg
  ports: 
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: bolg
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bolg
        tier: frontend
        track: stable
        run: angular-bolg
    spec:
      containers:
      - name: angular-bolg
        image: gcr.io/bolg-229922/angular-bolg:latest
        ports:
        - containerPort: 80
