apiVersion: apps/v1
kind: Deployment
metadata:
  name: bolg
spec:
  selector:
    matchLabels:
      app: bolg
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bolg
        tier: backend
        track: stable
    spec:
      containers:
        - name: bolg
          image: "gcr.io/bolg-229922/bolg:latest"
          command: ["app"]
          ports:
            - name: http
              containerPort: 80
